version: '3.2'

services:

  check_buy_land:
    build:
      context: ./
    command: [ "yarn", "start" ]

  test_unit:
    build:
      context: ./
    command: [ "yarn", "test:unit" ]

  linter:
    build:
      context: ./
    command: [ "yarn", "lint" ]
